import Head from "next/head";
import Header from "../components/Header";
import { useMoralis } from "react-moralis";
import { useState, useEffect } from "react";
import { useWeb3Contract } from "react-moralis";
import main from "../contracts/main.json";
import { ethers } from "ethers";
import Selector from "../components/Selector";

export default function Home() {
  const { Moralis, isWeb3Enabled, chainId: chainIdHex, account } = useMoralis();
  const [arr, setarr] = useState([]);
  const [sellerpan, setsellerpan] = useState("");
  const [buyerpan, setbuyerpan] = useState("");
  const [amount, setamount] = useState("");
  const [desc, setdesc] = useState("");
  const [query, setquery] = useState("");

  const mainaddress = "0x64F8C7C97196dFDA93d24e0540362d750241216E";

  const { runContractFunction: getinvoices } = useWeb3Contract({
    abi: main,
    contractAddress: mainaddress,
    functionName: "getinvoices",
    params: {},
  });

  const {
    runContractFunction: create_invoice,
    isFetching,
    isLoading,
  } = useWeb3Contract({
    abi: main,
    contractAddress: mainaddress,
    functionName: "create_invoice",
    params: {
      _buyer_pan: buyerpan,
      _seller_pan: sellerpan,
      _amount: amount,
      _desc: desc,
    },
  });

  async function updateUIValues() {
    const finalarr = await getinvoices();
    setarr(finalarr);
  }

  useEffect(() => {
    if (isWeb3Enabled) {
      updateUIValues();
    }
  }, [isWeb3Enabled]);

  const handleNewNotification = () => {
    dispatch({
      type: "info",
      message: "INVOICE CREATED",
      title: "INVOICE CREATED",
      position: "topR",
      icon: "bell",
    });
  };
  const handleSuccess = async (tx) => {
    try {
      await tx.wait(1);
      handleNewNotification(tx);
    } catch (error) {
      console.log(error);
    }
  };

  function mapper(contracts) {
    if (contracts[6] == false) {
      return (
        <div>
          <div className="flex justify-center">
            <div className=" m-3 p-2  w-2/3 bg-white rounded-md  mb-3">
              <span>Invoice Number:</span>
              <span>{contracts[0].toString()}</span>
              <br />
              <span>Paid/Settled:</span>
              <span>{contracts[5].toString()}</span>
              <br />
              <span>Buyer Pan:</span>
              <span>{contracts[1]}</span>
              <br />
              <span>Seller Pan:</span>
              <span>{contracts[2]}</span>
              <br />
              <span>Amount (in ETH):</span>
              <span>{ethers.utils.formatEther(contracts[3])}</span>
              <br />
              <div>Creator:</div>
              <div>{contracts[7].toString()}</div>
              <div className="flex">
                <div>Description:</div>
                <div>{contracts[4]}</div>
              </div>
            </div>
          </div>
        </div>
      );
    }
  }

  return (
    <>
      <Head>
        <title>Invoices</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Selector />

      <div className="flex justify-center">
        <div className=" h-60  w-1/3 bg-white rounded-md ">
          <div className="flex justify-center">
            <h1 className="font-bold m-2">Create Invoice:</h1>
          </div>
          <label>Buyer Pan:</label>
          <input
            placeholder="Pan of buyer"
            onChange={(e) => setbuyerpan(e.target.value)}
          />
          <br />
          <label>Seller Pan:</label>
          <input
            placeholder="Pan of seller"
            onChange={(e) => setsellerpan(e.target.value)}
          />
          <br />
          <label>Amount (in ETH):</label>
          <input
            placeholder="For eg: 0.01"
            type="number"
            onChange={(e) =>
              e.target.value
                ? setamount(
                    ethers.utils
                      .parseEther(e.target.value.toString())
                      .toString()
                  )
                : ""
            }
          />
          <br />
          <div className="flex">
            <label>Description:</label>
            <textarea
              placeholder="Product/Service description"
              onChange={(e) => setdesc(e.target.value)}
            />
          </div>
          <button
            className=" bg-slate-500 px-4 py-2 rounded-lg hover:text-slate-50"
            disabled={isLoading || isFetching}
            onClick={async () =>
              await create_invoice({
                onSuccess: handleSuccess,
                onError: (error) => console.log(error),
              })
            }
          >
            {isLoading || isFetching ? (
              <div className="animate-spin spinner-border h-8 w-8 border-b-2 rounded-full p-3"></div>
            ) : (
              "Create Invoice"
            )}
          </button>
        </div>
      </div>

      <div className="flex justify-center">
        <input
          placeholder="Search by Seller PAN / Invoice Number"
          onChange={(e) => setquery(e.target.value.toLowerCase())}
          class="p-4 rounded-full  w-96 mt-8 mb-14"
          style={{ backgroundColor: "#272727" }}
        />
      </div>

      {arr ? (
        <div className=" w-full grid grid-cols-2">
          {arr
            .filter(
              (contract) =>
                contract[2].toLowerCase().includes(query) ||
                parseInt(contract[0]).toString().includes(query) ||
                contract[4].toLowerCase().includes(query)
            )
            .map(mapper)}{" "}
        </div>
      ) : (
        <div class="flex justify-center mt-8">
          <div>Connect to Goerli Test-net!</div>
        </div>
      )}
    </>
  );
}
